apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: hawtio-operator-webhook-cert
  creationTimestamp: null
  name: hawtio-operator-webhook-service
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 9443
  selector:
    name: hawtio-operator
status:
  loadBalancer: {}
