apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hawtio

resources:
- ../base
- webhook-service.yaml
- webhook.yaml

patches:
- path: patch_operator.yaml
  target:
    kind: Deployment
    name: hawtio-operator
