apiVersion: v1
kind: Service
metadata:
  name: hawtio-operator-webhook-service
  annotations:
    # Automatically create a TLS secret
    service.beta.openshift.io/serving-cert-secret-name: hawtio-operator-webhook-cert
spec:
  selector:
    # Must match the label selector of Operator's Deployment Pod template
    name: hawtio-operator
  ports:
  - name: webhook
    port: 443
    targetPort: 9443
