apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hawtio

resources:
- ../base
- operator_signer_key_reader_role.yaml

patches:
- path: patch_cluster_role.yaml
  target:
    kind: ClusterRole
    name: hawtio-operator-cluster-role

#
# Patch to ensure the namespace of the signer-key role
# is not overwritten by kustomize. By making it a transformer
# it is performed at the end of the kustomize process.
#
transformers:
- |
  apiVersion: builtin
  kind: PatchTransformer
  metadata:
    name: fix-service-ca-namespace
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: openshift-service-ca
  target:
    kind: Role
    name: hawtio-operator-signing-key-reader
