apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hawtio-operator-signing-key-reader
  namespace: openshift-service-ca
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["signing-key"]
  verbs: ["get"]
