# Required to create a role-binding for access to
# the key signer on OpenShift
#
- op: add
  path: /rules/-
  value:
    apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["create"]

# Adds permission to bind to the dynamic target Role once its created
- op: add
  path: /rules/-
  value:
    apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles"]
    resourceNames: ["hawtio-operator-signing-key-reader"]
    verbs: ["bind"]

# Required for management of the hawtio-online proxy
# certificate in tenant namespaces on OpenShift
#
- op: add
  path: /rules/-
  value:
    apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete"]

# Required for checking if user is allowed
# to create custom routes
#
- op: add
  path: /rules/-
  value:
    apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]

# Required for administration of routes on OpenShift
#
- op: add
  path: /rules/-
  value:
    apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["create", "delete", "get", "list", "update", "patch", "watch"]

- op: add
  path: /rules/-
  value:
    apiGroups: ["route.openshift.io"]
    resources: ["routes/custom-host"]
    verbs: ["create", "update", "patch"]

# Required for creating, modifying, deleting
# console links and console yaml samples
#
- op: add
  path: /rules/-
  value:
    apiGroups: ["console.openshift.io"]
    resources: ["consolelinks", "consoleyamlsamples"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

# Required for creating, modifying oauthclient
# resources for authentication access
#
- op: add
  path: /rules/-
  value:
    apiGroups: ["oauth.openshift.io"]
    resources: ["oauthclients"]
    verbs: ["create", "get", "list", "update", "watch"]

# Required to determine the version of the
# OCP cluster (see capabilites package)
- op: add
  path: /rules/-
  value:
    apiGroups: ["config.openshift.io"]
    resources: ["clusterversions"]
    verbs: ["get"]
