apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hawtio-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - watch
    - create
    - delete
    - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes/custom-host
  verbs:
  - create
- apiGroups:
  - template.openshift.io
  resources:
  - processedtemplates
  verbs:
  - '*'
- apiGroups:
  - hawt.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
    - batch
  resources:
    - cronjobs
  verbs:
    - get
    - watch
    - list
    - update
    - create
    - delete

