about:
  title: Hawtio Online Console
  productInfo: []
  additionalInfo: The Hawtio Online Console eases the discovery and management of 'hawtio-enabled'
    applications deployed on OpenShift.
  imgSrc: /online/hawtio-logo.svg
branding:
  appName: Hawtio Online Console
  appLogoUrl: /online/hawtio-logo.svg
  favicon: /online/favicon.ico
  showAppName: true
login:
  title: Log in with your token
