apiVersion: hawt.io/v2
kind: Hawtio
metadata:
  name: hawtio-online
spec:
  type: Cluster

  # Included for backward compatibility - not used in hawtio-online 2.0.0+
  version: "1.12"

  replicas: 1
  auth:
    internalSSL: true
    clientCertCheckSchedule: "* */12 * * *"
    clientCertExpirationPeriod: 24

  resources:
    limits:
      cpu: "1"
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 32Mi
