apiVersion: hawt.io/v1
kind: Hawtio
metadata:
  name: hawtio-online
spec:
  type: Namespace
  replicas: 1
  auth:
    clientCertCheckSchedule: "* */12 * * *"
    clientCertExpirationPeriod: 24

  resources:
    limits:
      cpu: "1"
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 32Mi
