name: Build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  # Allow manual run if necessary
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.26.5"]
        arch: [ amd64, arm64 ]
    steps:
      - name: Install QEMU static binaries for Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support
      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Cache modules
        uses: actions/cache@v6
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build on ${{matrix.arch}}
        run: |
          ARCHS=${{matrix.arch}} make build
      - name: Build image on ${{matrix.arch}}
        run: |
          ARCHS=${{matrix.arch}} make image
      - name: Display image
        run: |
          make list-images
